# Generated by Django 5.2.8 on 2025-11-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
